USE [master]
GO

/****** Object:  Database [Budgeting]    Script Date: 7/26/2024 11:53:07 PM ******/
DROP DATABASE [Budgeting]
GO

/****** Object:  Database [Budgeting]    Script Date: 7/26/2024 11:53:07 PM ******/
CREATE DATABASE [Budgeting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Budgeting', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Budgeting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Budgeting_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Budgeting_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Budgeting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Budgeting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Budgeting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Budgeting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Budgeting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Budgeting] SET ARITHABORT OFF 
GO

ALTER DATABASE [Budgeting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Budgeting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Budgeting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Budgeting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Budgeting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Budgeting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Budgeting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Budgeting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Budgeting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Budgeting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Budgeting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Budgeting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Budgeting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Budgeting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Budgeting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Budgeting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Budgeting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Budgeting] SET RECOVERY FULL 
GO

ALTER DATABASE [Budgeting] SET  MULTI_USER 
GO

ALTER DATABASE [Budgeting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Budgeting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Budgeting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Budgeting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Budgeting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Budgeting] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Budgeting] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Budgeting] SET  READ_WRITE 
GO


