USE [Budgeting]
GO

/****** Object:  Table [dbo].[BUDGET_GOAL]    Script Date: 8/3/2024 4:14:54 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BUDGET_GOAL]') AND type in (N'U'))
DROP TABLE [dbo].[BUDGET_GOAL]
GO

/****** Object:  Table [dbo].[BUDGET_GOAL]    Script Date: 8/3/2024 4:14:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUDGET_GOAL](
	[BUDGET_GOAL_ID] [bigint] IDENTITY(110,1) NOT NULL,
	[BUDGET_GOAL_AMOUNT] [money] NULL,
	[DAILY_PROGRESS] [nchar](10) NOT NULL,
	[MONTHLY_PROGRESS] [money] NULL,
	[GOAL_DATE] [money] NULL,
	[PROJECTED_GOAL_COMPLETION] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[BUDGET_GOAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
GO


