USE [SimTickerData]
GO

/****** Object:  Table [dbo].[INCREMENTAL_IDENTIFIERS]    Script Date: 6/9/2024 10:58:14 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INCREMENTAL_IDENTIFIERS]') AND type in (N'U'))
DROP TABLE [dbo].[INCREMENTAL_IDENTIFIERS]
GO

/****** Object:  Table [dbo].[INCREMENTAL_IDENTIFIERS]    Script Date: 6/9/2024 10:58:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INCREMENTAL_IDENTIFIERS](
	[INC_REFERENCE_ID] [uniqueidentifier] NOT NULL,
	[TABLE_NAME] [nvarchar](50) NULL,
	[NEXT_IDENTIFIER] [numeric](18, 0) NULL,
 CONSTRAINT [PK_INCREMENTAL_IDENTIFIERS] PRIMARY KEY CLUSTERED 
(
	[INC_REFERENCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


