USE [Budgeting]
GO

/****** Object:  Table [dbo].[SPENDING_RECURRING]    Script Date: 8/3/2024 4:14:54 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPENDING_RECURRING]') AND type in (N'U'))
DROP TABLE [dbo].[SPENDING_RECURRING]
GO

/****** Object:  Table [dbo].[SPENDING_RECURRING]    Script Date: 8/3/2024 4:14:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPENDING_RECURRING](
	[SPENDING_ITEM_ID] [bigint] IDENTITY(110,1) NOT NULL,
	[MONTHLY_SPEND] [money]  NULL,
	[MONTHLY_SPEND_C] AS ISNULL(YEARLY_SPEND / 12,0) PERSISTED,
	[YEARLY_SPEND] [money]  NULL,
	[YEARLY_SPEND_C] AS ISNULL(MONTHLY_SPEND * 12,0) PERSISTED
PRIMARY KEY CLUSTERED 
(
	[SPENDING_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
GO


