/****** Object:  Trigger [dbo].[TRG_FOOD_PANTRY_I]    ******/
CREATE TRIGGER [dbo].[TRG_FOOD_PANTRY_IU]
	ON [dbo].[FOOD_PANTRY]
	FOR INSERT
	AS
	BEGIN
		SET NOCOUNT ON

		IF (ROWCOUNT_BIG() = 0)
			RETURN;

		INSERT INTO FOOD_PANTRY_PRICE_HISTORICAL
		(
		FOOD_ITEM_ID,
		ITEM_NAME,
		PRICE,
		AS_OF_DATE
		)
		SELECT 
		FOOD_ITEM_ID,
		ITEM_NAME,
		MOST_RECENT_PRICE,
		GETDATE()
		FROM INSERTED

	END
GO

