CREATE TABLE [dbo].[BUDGET]
(
	[BUDGET_ID] BIGINT IDENTITY(1,1) PRIMARY KEY, 
    [USER_ID] BIGINT NULL, 
    [TOTAL_SPENDING] MONEY NULL, 
    [TOTAL_REVENUE] MONEY NULL, 
    CONSTRAINT [FK_BUDGET_USERS] FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
