CREATE TABLE [dbo].[BUDGET_GOAL] (
    [BUDGET_GOAL_ID]            BIGINT     IDENTITY (110, 1) NOT NULL,
    [BUDGET_GOAL_AMOUNT]        MONEY      NULL,
    [DAILY_PROGRESS]            NCHAR (10) NOT NULL,
    [MONTHLY_PROGRESS]          MONEY      NULL,
    [GOAL_DATE]                 MONEY      NULL,
    [PROJECTED_GOAL_COMPLETION] DATETIME   NULL,
    [BUDGET_ID] BIGINT NULL, 
    [CURRENT_AMOUNT_SAVED] MONEY NULL, 
    [PERCENT_COMPLETE] DECIMAL NULL, 
    PRIMARY KEY CLUSTERED ([BUDGET_GOAL_ID] ASC), 
    CONSTRAINT [FK_BUDGET_GOAL_BUDGET] FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET(BUDGET_ID)
);

