CREATE TABLE [dbo].[FOOD_PANTRY]
(
	[FOOD_ITEM_ID] BIGINT IDENTITY(1,1) PRIMARY KEY, 
    [ITEM_NAME] VARCHAR(200) NULL, 
    [ITEM_DESCRIPTION] VARCHAR(2000) NULL, 
    [MOST_RECENT_PRICE] MONEY NULL, 
    [MOST_RECENT_PURCHASE_DATE] DATETIME NULL, 
    [USE_BY] DATETIME NULL, 
    [EXPIRATION_DATE] DATETIME NULL, 
    [USER_ID] BIGINT NULL, 
    [SPENDING_ITEM_ID] BIGINT NULL, 
    CONSTRAINT [FK_FOOD_PANTRY_SPENDING] FOREIGN KEY (SPENDING_ITEM_ID, USER_ID) REFERENCES SPENDING(SPENDING_ITEM_ID, USER_ID)
)

GO

CREATE INDEX [IX_FOOD_PANTRY_USER_FOOD] ON [dbo].[FOOD_PANTRY] (FOOD_ITEM_ID, USER_ID)
