CREATE TABLE [dbo].[FOOD_PANTRY_PRICE_HISTORICAL]
(
	[HISTORICAL_PRICE_ID] BIGINT IDENTITY(1,1) PRIMARY KEY, 
    [FOOD_ITEM_ID] BIGINT NULL, 
    [ITEM_NAME] VARCHAR(200) NULL, 
    [PRICE] MONEY NULL, 
    [AS_OF_DATE] DATETIME NULL, 
    CONSTRAINT [FK_FOOD_PANTRY_PRICE_HISTORICAL_FOOD_PANTRY] FOREIGN KEY (FOOD_ITEM_ID) REFERENCES FOOD_PANTRY(FOOD_ITEM_ID)
)
