CREATE TABLE [dbo].[SPENDING]
(
	[SPENDING_ITEM_ID] BIGINT IDENTITY(10,1) PRIMARY KEY, 
    [SOURCE] VARCHAR(200) NULL, 
    [DATE] DATETIME NOT NULL DEFAULT GetDate(), 
    [CATEGORY] VARCHAR(50) NULL, 
    [USER_ID] BIGINT NOT NULL, 
    CONSTRAINT [FK_SPENDING_USERS] FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID), 
    CONSTRAINT [AK_SPENDING_SPEND_USER] UNIQUE (SPENDING_ITEM_ID,USER_ID)
)
