CREATE TABLE [dbo].[SPENDING_RECURRING] (
    [RECURRING_SPENDING_ITEM_ID] BIGINT IDENTITY (110, 1) NOT NULL,
    [MONTHLY_SPEND]    MONEY  NULL,
    [MONTHLY_SPEND_C]  AS     (isnull([YEARLY_SPEND]/(12),(0))) PERSISTED NOT NULL,
    [YEARLY_SPEND]     MONEY  NULL,
    [YEARLY_SPEND_C]   AS     (isnull([MONTHLY_SPEND]*(12),(0))) PERSISTED NOT NULL,
    [USER_ID] BIGINT NOT NULL, 
    PRIMARY KEY CLUSTERED ([RECURRING_SPENDING_ITEM_ID] ASC), 
    CONSTRAINT [FK_SPENDING_RECURRING_USERS] FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

